compile:
  stage: build
  image: thomasweise/docker-texlive-full
  script:
    - mkdir -p out
    - ./MAKEALL
    - ls out
  artifacts:
    paths: 
      - out
    expire_in: 1 hour

pages:
  stage: deploy
  script:
    - mkdir public
    - mv out/* public/
  artifacts:
    paths: 
      - public
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_BRANCH == "main"