default:
  image: thomasweise/docker-texlive-full

compile:
  stage: build
  script:
    - mkdir -p out
    - ./MAKEALL
    - ls out
  artifacts:
    paths: 
      - out

pages:
  stage: deploy
  script:
    - mkdir public
    - mv out/* public/
  artifacts:
    paths: 
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"