default:
  image: thomasweise/docker-texlive-thin

compile:
  stage: build
  script:
    - ./MAKEALL
  artifacts:
    paths: 
      - out

pages:
  stage: deploy
  script:
    - mkdir public
    - mv out/* public/
  artifacts:
    paths: 
      - public
  only: 
    - master