documents:
  stage: build
  image: thomasweise/docker-texlive-full
  script:
    - mkdir -p out
    - ./MAKEALL
    - ls out
  artifacts:
    paths: 
      - out
    expire_in: 1 hour

variables:
  GIT_SUBMODULE_STRATEGY: recursive

website:
  stage: build
  image:
    name: klakegg/hugo
    entrypoint: [""]
  script:
    - mkdir -p out
    - cd ./docs/site/
    - hugo
    - mv -v ./public/* ../../out/
  artifacts:
    paths:
    - public
    expire_in: 1 hour

pages:
  stage: deploy
  script:
    - mkdir public
    - mv out/* public/
  artifacts:
    paths: 
      - public
    expire_in: 1 day