documents:
  stage: build
  image: thomasweise/docker-texlive-full
  script:
    - mkdir -p out
    - ./MAKEALLDOCS
    - ls out
  artifacts:
    paths: 
      - out
    expire_in: 1 hour

variables:
  GIT_SUBMODULE_STRATEGY: recursive

website:
  stage: build
  image:
    name: klakegg/hugo:ext-alpine-ci
    entrypoint: [""]
  script:
    - mkdir -p out
    - cd ./docs/site/
    - hugo -t hugo-theme-shell
    - mv -v ./public/* ../../out/
  artifacts:
    paths:
    - out
    expire_in: 1 hour

#notebooks:
#  stage: build
#  image: bgameiro/arch-jupyterlab
#  script:
#    - mkdir -p out
#    - ./MAKEALLNB
#    - ls out
#  artifacts:
#    paths: 
#      - out
#    expire_in: 1 hour

pages:
  stage: deploy
  script:
    - mkdir public
    - mv out/* public/
  artifacts:
    paths: 
      - public
    expire_in: 1 day