#!/usr/bin/env bash

jupyter nbconvert --execute --to html PyROOT_resolution_Cs137v1.ipynb
jupyter nbconvert --execute --to html PyROOT_resolution_Cs137v2.ipynb
jupyter nbconvert --execute --to html PyROOT_resolution_Cs137v3.ipynb